export const FETCH_CATEGORY_POSTS = 'FETCH_CATEGORY_POSTS';
export const FETCH_ALL_POSTS = 'FETCH_ALL_POSTS'
export const CREATE_POST = 'CREATE_POST'
export const GET_SINGLE_POST = 'GET_SINGLE_POST'
export const VOTE_ON_POST = 'VOTE_ON_POST'
export const EDIT_POST=  'EDIT_POST'
export const DELETE_POST = 'DELETE_POST'
export const POST_SORT_ORDER = 'POST_SORT_ORDER'